### ISSUE TITLE
Menú superior

### ISSUE THREAD

**Issue by lecovi** [PyAr/asoc_members#102]
Se necesita un menú para poder navegar entre secciones.

Es muy molesto tener que volver al home para poder cambiar de sección.

**Comment by facundobatista** [comment]
Cuales serían los items del menú? Los cuatro grandes botones que tenemos en el home?

**Comment by lecovi** [comment]
Si, de mínima los botones de:

- Inicio
- Eventos
  - Patrocinios
- Organizadores
- Sponsors
- Proveedores
- Reportes

**Comment by lecovi** [comment]
Esto lo tenemos en la barra de navegación ahora.
