### ISSUE TITLE
No se puede ver un sponsor via admin

### ISSUE THREAD

**Issue by facundobatista** [PyAr/asoc_members#105]
Fui al admin -> sponsors, hice click en Kilimo, fue a [esta url](https://admin.ac.python.org.ar/admin/events/sponsor/17/change/), me dio 500

**Comment by andresramirezmiori** [comment]
este creo que ya esta cerrado, desde el ultimo feature mergeado, faltaba una coma en la lista de campos a mostrar creo

**Comment by facundobatista** [comment]
Sí, este está listo!! Gracias!
