### ISSUE TITLE
Detalles en la asociación de sponsor con categoría, en un evento

### ISSUE THREAD

**Issue by facundobatista** [PyAr/asoc_members#106]
Ejemplo, en [esta página](https://admin.ac.python.org.ar/eventos/eventos/2/patrocinios/crear/), hay dos cosas a cambiar:

- el título de la primer opción está pegado: `Sponsorcategory*`

- el combobox de la segunda opción está desordenado

**Comment by lecovi** [comment]
Si mergeamos #206 esto queda fixeado y podemos cerrar el issue
<img width="1155" alt="Screen Shot 2021-05-25 at 15 07 21" src="https://user-images.githubusercontent.com/6667873/119547020-f6384d00-bd6a-11eb-8d78-1c2c204dc022.png">
