### ISSUE TITLE
Testear funcionalidades críticas

### ISSUE THREAD

**Issue by cmdelatorre** [PyAr/asoc_members#11]
Durante el PyCamp generamos funcionalidades para:
* cargar pagos automáticamente desde MercadoLibre
* Crear automáticamente las cuotas a partir de un pago

Ambas funcionalidades deben ser detalladamente monitoreadas y testeadas. Hay muchos corner cases y cosas que pueden fallar.

Progresivamente, hay que hacer esas funcionalidades más robustas.

**Comment by facundobatista** [comment]
De los pagos normales ya está, falta lo de mercadopago
