### ISSUE TITLE
Cuando se va a facturar un patrocinio la página no muestra la info necesaria

### ISSUE THREAD

**Issue by facundobatista** [PyAr/asoc_members#112]
Ejemplo [esta página](https://admin.ac.python.org.ar/eventos/eventos/patrocinios/25/) que es la que apunta del home page a nivel de "tarea". 

Uno va ahí porque el sistema dice "che, tenés que generar la factura", pero no está la info de qué hay que facturar...

Tiene que mostrar:
- el monto a facturar
- los datos del sponsor

(los datos del sponsor ya están, pero ocultos por default)

**Comment by lecovi** [comment]
Si mergeamos #206 podemos cerrar este issue. 
<img width="1143" alt="Screen Shot 2021-05-25 at 14 57 46" src="https://user-images.githubusercontent.com/6667873/119545883-ab6a0580-bd69-11eb-8281-777edaa3675d.png">
<img width="825" alt="Screen Shot 2021-05-25 at 14 57 53" src="https://user-images.githubusercontent.com/6667873/119545892-ae64f600-bd69-11eb-978b-3f966466ee17.png">

**Comment by facundobatista** [comment]
No entiendo, en el primer screenshot que ponés acá NO aparece el monto a facturar (que es lo que estoy indicando arriba).

También estaría bueno que esté la fecha de creación del item.

**Comment by lecovi** [comment]
Ahhh, tenés razón, en el primer Screenshot no aparece. Sí aparece en el Modal.

**Comment by lecovi** [comment]
Ahí le agregué el valor al lado del nombre de la categoría
<img width="1119" alt="Screen Shot 2021-06-04 at 21 54 05" src="https://user-images.githubusercontent.com/6667873/120874940-6a4ece00-c57f-11eb-9766-fa3dd774f8cf.png">

Por la fecha de creación del ítem hablamos de la fecha de creación del sponsoreo, no?

**Comment by lecovi** [comment]
Así te parece viable?

<img width="1132" alt="Screen Shot 2021-06-04 at 22 05 55" src="https://user-images.githubusercontent.com/6667873/120875204-12b16200-c581-11eb-8be5-1d7152fedac3.png">

**Comment by lecovi** [comment]
Y así el detalle en la factura y en la afectación:
<img width="1164" alt="Screen Shot 2021-06-04 at 22 14 28" src="https://user-images.githubusercontent.com/6667873/120875470-5c4e7c80-c582-11eb-942e-2e4d869fcc73.png">

**Comment by facundobatista** [comment]
Buenísimo!
