### ISSUE TITLE
Que el CUIT sea opcional

### ISSUE THREAD

**Issue by facundobatista** [PyAr/asoc_members#128]
Sino, ¿cómo cargamos sponsors no Argentinos?

**Comment by facundobatista** [comment]
Ojo, este issue está relacionado desde ese branch, pero no tiene nada que ver...

**Comment by samsagaz** [comment]
@facundobatista, el branch de @eduzen arregla el CUIT en  BankAccountData, pero el problema está en el modelo Sponsor (linea 299)

Entiendo que hay dos caminos...

1 - Agregar un campo nuevo para sponsors que no sean de Argentina y poner el CUIT como opcional.

2 - Dejar de usar el nombre CUIT y ponerle simplemente "Identificación Tributaria", modificar el max_length (actualmente es 13), quitarle la validación del field y dejarlo como está ahora, "requerido". 

Opiniones? Alternativas?

**Comment by facundobatista** [comment]
Medio marcha atrás con este issue! Ayer hice dos facturas internacionales, y resulta que igual hay que cargar un CUIT! Así que mejor tenerlo en este campo acá!

El CUIT en los casos de las facturas de exportación es por pais; por ejemplo para Estados Unidos (personas jurídicas) el CUIT es 55-00000212-6.

Entonces, lo que tenemos que hacer acá es dejar el CUIT mandatorio, pero asegurarnos que estos CUITs "raros" pasen la validación OK.

Puntos extras si uno puede pegar en ese campo el cuit *sin* los guiones (lo podría acomodar sólo).

Gracias!
