### ISSUE TITLE
post_save de Payments

### ISSUE THREAD

**Issue by cmdelatorre** [PyAr/asoc_members#14]
Hay una signal de post_save que crea automáticamente las cuotas a partir de un pago. Como todo, puede fallar. Hay que analizar bien qué hace falta registrar y cómo. ¿Alarmas, alertas, etc?

**Comment by facundobatista** [comment]
Estoy re-armando la estructura de pagos a partir de cargas reales y lo que puse en el Doc. Este issue quedó obsoleto, then....
