### ISSUE TITLE
Que los gastos se puedan "cancelar"

### ISSUE THREAD

**Issue by facundobatista** [PyAr/asoc_members#146]
Es un flag de "cancelado", con una fecha de cancelación.

Podría ser también un "cancelled_date" como campo, y un property de ".cancelled" que se fije se la fecha de cancelación es None o no.

En la vista del gasto ([ejemplo](https://admin.ac.python.org.ar/eventos/eventos/gasto_proveedor/59/)) tiene que haber un botón "cancelar", que cuando une hace click ahí te pida confirmación.

No hace falta un mecanismo para "reactivar" (de última se puede hacer via admin).

**Comment by samsagaz** [comment]
La idea es poder cancelar el gasto completo del proveedor?
o la factura? o el recibo? o cada cosa por separado ? (por lo pronto veo que no se puede borrar la factura, el recibo ni el gasto completo)

**Comment by facundobatista** [comment]
Cancelar el gasto completo, se le pueden cargar cosas, pero que quede cancelado (y que se muestre en el listado, cancelado)

**Comment by samsagaz** [comment]
![image](https://user-images.githubusercontent.com/5218613/70850177-31400c80-1e66-11ea-8b88-634246f4812b.png)
así te parece bien que lo muestre?

**Comment by samsagaz** [comment]
El reintegro no hace falta cancelarlo?
