### ISSUE TITLE
Error en make build-dev

### ISSUE THREAD

**Issue by eamanu** [PyAr/asoc_members#148]
Buenas, 

Cuando hago un `make buid-dev` durante la instalación del requirements salta el siguiente error:

```
ERROR: azure 4.0.0 has requirement azure-storage-blob~=1.3, but you'll have azure-storage-blob 12.1.0 which is

**Comment by facundobatista** [comment]
Estoy tratando de reproducirlo... creo haber visto esto cuando quise deployar una nueva versión a prod y explotó... sospecho un par de cambios que entraron sugeridos automáticamente por seguridad (versiones de dependencias)... no sé cómo los tests pasaron con esos cambios, sin embargo

**Comment by facundobatista** [comment]
A mí no me pasa :/  https://gist.github.com/facundobatista/2c485b5b1da7d8e1abb6182ab6ed4ca6

**Comment by eamanu** [comment]
Hmm si haciendo un make clean-dev no salta el error. Pero si me aparece si estoy en un host "limpio". (yo corro esto: `docker kill $(docker ps -q) ; docker rm $(docker ps -a -q) ; docker rmi -f $(docker images -q -a) ;docker volume rm -f $(docker volume ls  -q)`)

https://gist.github.com/eamanu/ad59247912d5e6469d094df240d4a850

**Comment by eduzen** [comment]
@eamanu  podes correr `docker system prune` para limpiar containers imagenes y demases. Si ademas queres borrar volumentes `docker system prune --volumes`

**Comment by facundobatista** [comment]
@eduzen ¿por qué cerraste el issue? 

Acá estamos medio trackeando dos cosas (sí, no es la forma más limpia, pero es que no sabemos exactamente qué pasa).

Por un lado, en containers limpios, master está roto:
- esto lo ve @eamanu cuando dice "pero sí me aparece si estoy en un host limpio"
- quise deployar prod y explotó todo (estoy esperando que armen staging para poder probar deploy sin afectar el servicio...)

Por otro lado, la infra de desarrollo no limpia bien:
- localmente, el problema no aparece, hay *algo* que es distinto a "tener todo limpio"
- `make clean-dev` debería limpiar dev! no sé si estamos usando mal Docker o qué, pero es una garompa tener un dev sucio luego de `make clean-dev` y tener que hacer cosas raras a mano para "limpiar el entorno"

**Comment by facundobatista** [comment]
FWIW, estamos hablando de deployar a staging [acá](https://pyar.zulipchat.com/#narrow/stream/200416-Infra/topic/Staging.20de.20members.2Fevents)

**Comment by eduzen** [comment]
@facundobatista pense que era local 🙈! Perdonen

**Comment by samsagaz** [comment]
no logro reproducir el error, a mi anda bien el make build-dev del branch master

**Comment by facundobatista** [comment]
Este problema lo fixeamos [hoy](https://github.com/PyAr/asoc_members/commit/2452d0ecc0cea745f75374c5872bb55795ad7883). Resulta que algunas dependencias eran poco compatibles entre sí, hoy upgradeamos una que acomoda sus propios requerimientos. 

(todo esto en el laburo de tener staging)

Entonces lo cierro,
