### ISSUE TITLE
Flag de "ya aceptó ser colaborador"

### ISSUE THREAD

**Issue by facundobatista** [PyAr/asoc_members#18]
Para los socios colaboradores necesitamos un flag más en el modelo que indique que realizó el proceso para ser colaborador, default a False en caso de ser colaborador, nullable (para los no colaboradores) y que se pondría en True a mano..

**Comment by samsagaz** [comment]
Creo que ya está implementado en el modelo (o no entiendo el issue)
`
has_collaborator_acceptance = models.BooleanField(_('ha aceptado ser colaborador?'), default=False)
`

**Comment by facundobatista** [comment]
Yes! Gracias
