### ISSUE TITLE
Género en nacionalidad y estado civil

### ISSUE THREAD

**Issue by facundobatista** [PyAr/asoc_members#19]
Hay que definir si un hombre es "argentinA", porque "la nacionalidad", y una mujer es "casado", por "el estado civil", o qué....

**Comment by facundobatista** [comment]
Mmm... ahora que decís "dropdown"... ¿género y estado civil no son free text? Más allá de lo que hablamos con @matuu sobre control de mayúsculas/minusculas, quizás lo mejor es dejar lo que ponga la persona y ya...

**Comment by cmdelatorre** [comment]
Todo depende para qué queremos el dato. Si es exclusivamente para cumplir con regulaciones: free-text y chau.

Si en algún momento vamos a querer hacer algún tipo de análisis, vamos a necesitar decidir los valores posibles (y cómo _mostrarlos_ de manera inclusiva y razonable)

**Comment by facundobatista** [comment]
Yo lo dejaría libre. 

No le ponemos restricciones a nadie :). Por otro lado, es más carga para la persona (tener que escribirlo, en vez de seleccionarlo), pero no creo que sea demasiado, y es algo que se hace *una vez*.

Por eso, libre.

**Comment by facundobatista** [comment]
Libre!
