### ISSUE TITLE
Fix visualización de paginación

### ISSUE THREAD

**Issue by lecovi** [PyAr/asoc_members#218]
Hay que agregar los estilos de la paginación según Bootstrap4: https://getbootstrap.com/docs/4.0/components/pagination/
![Screen Shot 2021-07-20 at 13 51 22](https://user-images.githubusercontent.com/6667873/126364140-4a5371e4-8129-4992-810e-7a613088ccb7.png)

**Comment by cmdelatorre** [comment]
Parece que ya lo agarraron (estoy en el main del repo). ¿a cerrarlo? ¿o esperan a que esté desplegado para cerrar el issue?

![image](https://user-images.githubusercontent.com/3369460/142945160-0d68036f-4245-4c74-919e-4cee160509f1.png)

**Comment by cmdelatorre** [comment]
Aunque veo que en /reportes/miembros no aplica el estilo ¿la idea es buscarlo y aplicarlo en todos lados, me imagino?

**Comment by facundobatista** [comment]
No sé... @lecovi ?

**Comment by lecovi** [comment]
ja! re tarde... pero si, la idea es aplicarlo en todos lados...
