### ISSUE TITLE
Fix Botón "Agregar Organizadores" en la pantalla de "Eventos"

### ISSUE THREAD

**Issue by lecovi** [PyAr/asoc_members#219]
Si estamos viendo los detalles de un evento, tenemos un botón que dice `+ Agregar Organizadores` que debería decir `Vincular organizadores`.
![Screen Shot 2021-07-20 at 13 53 09](https://user-images.githubusercontent.com/6667873/126364524-566fc633-2034-4f6b-8a80-c74d64164cf6.png)

El flujo para crear organizadores nuevos es:
1. Ir a https://admin.ac.python.org.ar/eventos/organizadores/ y "Crear"
2. Agregar `username` y `mail`
3. Luego podemos vincular a esa persona al evento
4. El sistema le envía un correo a esa persona para que se registre en el sistema de eventos

**Comment by aayusranjan** [comment]
I like to help u, can u tell me in **English**

**Comment by cmdelatorre** [comment]
Está listo en main.

**Comment by facundobatista** [comment]
Closing, then, thanks!
