### ISSUE TITLE
Add Travis to this project

### ISSUE THREAD

**Issue by facundobatista** [PyAr/asoc_members#25]
This way we would never land code that fail tests

**Comment by eduzen** [comment]
@facundobatista can you add as a dev in this project?

Travis tells me that:

> You don't have sufficient rights to enable this repo on Travis. 
> Please contact the admin to enable it or to receive admin rights yourself.

**Comment by eduzen** [comment]
I opened [pull](https://github.com/PyAr/asoc_members/pull/34) with a .travis.yml  I need to activate the repo on travis and update the readme.

**Comment by facundobatista** [comment]
Hola! Ahí creo que te dí los permisos correctos para que hagas "lo que tengas que hacer". Si ves que todavía no, charlemos por Telegram así lo desculamos.

Abrazo!

**Comment by facundobatista** [comment]
Done!
