### ISSUE TITLE
Terminar / poner a punto la página donde se tiene que anotar alguien que quiere ser socio

### ISSUE THREAD

**Issue by facundobatista** [PyAr/asoc_members#43]
Está empezada, pero se cambiaron un poco los modelos y hay que ajustarla/terminarla.

**Comment by matuu** [comment]
Yo estuve haciendo esto en el pycamp pasado, pero terminarla en el que viene =)

**Comment by samsagaz** [comment]
lo hacemos???

**Comment by samsagaz** [comment]
> Yo estuve haciendo esto en el pycamp pasado, pero terminarla en el que viene =)

lo terminamos?
