### ISSUE TITLE
Hacer una página para ver mejor "una persona"

### ISSUE THREAD

**Issue by facundobatista** [PyAr/asoc_members#45]
Se necesita una página con un "buscar" que me encuentre N resultados, y al hacer click en uno de esos me despliegue info concentrada de esa persona:

- Los datos personales (no todos, hay que ver cuales tienen sentido)
- Los datos a nivel membership
- Las últimas N cuotas pagas

Podrian tener links donde correspondan a la página del admin correspondiente; en una segunda fase se puede revisar si se quiere que se administre todo de un sólo lado (creo que no se justifica)

**Comment by facundobatista** [comment]
Más detalle sobre qué mostrar:

Un text entry de search! que busque por: nombre, apellido, email, organización, dni, cuit

La búsqueda muestra:
    - si hay un solo match, directamente pasa a la vista de datos (ver abajo)
    - else: una lista de matches, y al hacer click en uno de esos, muestra la vista de datos (ver abajo)

La lista de matches es un match por renglón, cada renglón mostrando...

...si es una persona:
    - member.legal_id
    - person.first_name + person.last_name
    - person.document_number

...si es una orga:
    - member.legal_id
    - organization.name
    - organization.document_number

Adicionalmente, si está dado de baja, el renglón tiene que tener fondo rojo, letra gris clara.

El resultado final, la vista de datos, tiene que mostrar:
    - los datos del Member
    - los datos del Patron correspondiente
    - los datos del Person u Organization, según corresponda
    - las últimas 6 cuotas pagas, con su correspondiente info de Payment
    
Las cuotas deben tener un fondo rojo si es deudor. Los datos del Member que falten para que sea efectivamente socie tienen que estar resaltados también de alguna manera.

**Comment by samsagaz** [comment]
está bien este tipo de organización para la vista detallada de cada persona?

![image](https://user-images.githubusercontent.com/5218613/70408653-ac995c80-1a27-11ea-80ac-a8b51e8078df.png)
