### ISSUE TITLE
Borrar Información de la WIKI

### ISSUE THREAD

**Issue by samsagaz** [PyAr/asoc_members#56]
Quedó desactualizada la informaición contenida en la WIKI. TODO lo que aparece en ella no aplica para la app.

**Comment by facundobatista** [comment]
Qué página de la wiki?

**Comment by samsagaz** [comment]
https://github.com/PyAr/asoc_members/wiki

te resulta conocido lo que explica? :D

**Comment by samsagaz** [comment]
ZZZzzz

**Comment by facundobatista** [comment]
Done!
