### ISSUE TITLE
Dice "sin datos de facturación" pero el sponsor tiene todo cargado

### ISSUE THREAD

**Issue by facundobatista** [PyAr/asoc_members#97]
Es en esta [página](https://admin.ac.python.org.ar/eventos/eventos/patrocinios/1/), quizás se refiera  a que la factura no está hecha?

**Comment by andresramirezmiori** [comment]
hay paginas que al no ser organizador del evento no puedo ver pero como el link apunta al patrocinio y no al patrocinador imagino  que se refiere a la factura tal como decis

**Comment by lecovi** [comment]
Si, es un error en el mensaje. Es confuso, en #206 está fixeado. Se puede cerrar este issue cuando hagamos el merge.
